
{'date': 'Mon Jun 04 2018 15:16:33.992 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 49
    aventurasnaescola()
  module <module> line 21
    meio.vai = gogeo
NameError: name 'meio' is not defined
'''},
{'date': 'Mon Jun 11 2018 14:34:18.396 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    trigonometria().norte.vai()
  module <module> line 35
    TRIG = _sala = Sala(CLASE1,CLASSE2,CLASSE3,CLASSE4, "trig")
NameError: name 'CLASE1' is not defined
'''},
{'date': 'Mon Jun 18 2018 14:36:12.170 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 44
    trigonometria().norte.vai()
  module <module> line 35
    interruptor = Elemento(interruptor, tit = "inter", drag=True,
UnboundLocalError: local variable 'interruptor' referenced before assignment
'''},
{'date': 'Mon Jun 18 2018 14:36:39.738 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 44
    trigonometria().norte.vai()
  module <module> line 35
    interruptor = Elemento(interruptor, tit = "inter", drag=True,
UnboundLocalError: local variable 'interruptor' referenced before assignment
'''},
{'date': 'Mon Jun 18 2018 14:46:55.521 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 48
    trigonometria().norte.vai()
  module <module> line 39
    toma = Elemento(tomda, tit = "tomada", drag=True,
NameError: name 'tomda' is not defined
'''},
{'date': 'Tue Jul 17 2018 03:11:01.973 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 82
    trigonometria().norte.vai()
  module <module> line 59
    _sala.leste.meio = Cena(vai=_go_geography)
NameError: name '_go_geography' is not defined
'''},
{'date': 'Tue Jul 17 2018 03:16:13.605 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 26
  def go_trigonometria():
  ^
IndentationError: unexpected indent
'''},