
{'date': 'Mon Jun 04 2018 14:52:17.807 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jun 04 2018 14:54:14.852 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  def sala()
             ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 04 2018 14:54:56.771 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 29
    sala()    
  module <module> line 13
    INVENTARIO.inicia()
NameError: name 'INVENTARIO' is not defined
'''},
{'date': 'Mon Jun 04 2018 14:55:23.828 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 29
    sala()    
  module <module> line 16
    s_trig = Cena(CLASS23C, esquerda=e_trig, meio=Cena(vai=vai_geo))
NameError: name 'vai_geo' is not defined
'''},
{'date': 'Mon Jun 18 2018 14:14:12.351 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jun 18 2018 14:14:46.971 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 62
    INVENTARIO.inicia()
NameError: name 'INVENTARIO' is not defined
'''},
{'date': 'Mon Jun 18 2018 14:15:32.990 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 63
    trigonometria().norte.vai()
  module <module> line 46
    TRIG = _sala = Sala(CLASS23A,CLASS23B,CLASS23C,CLASS23D, "CLASS23")
NameError: name 'Sala' is not defined
'''},
{'date': 'Mon Jun 18 2018 14:16:03.366 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 63
    trigonometria().norte.vai()
  module <module> line 49
    vdgball = Elemento(ball, tit = "microscope", drag=True,
NameError: name 'ball' is not defined
'''},
{'date': 'Mon Jun 18 2018 14:36:16.673 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Oct 22 2018 10:05:26.160 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Aug 28 2019 10:53:02.680 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Oct 04 2019 20:08:37.301 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Oct 04 2019 20:09:46.253 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Oct 04 2019 20:10:09.672 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 13
  n_trig = Cena(CLASS23A)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Oct 04 2019 20:10:53.105 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    INVENTARIO.inicia()
NameError: name 'INVENTARIO' is not defined
'''},
{'date': 'Sat Oct 05 2019 10:33:49.946 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Nov 13 2019 17:57:59.965 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  INVENTARIO.inicia()
  ^
IndentationError: unexpected indent
'''},